# Generated by Django 5.2.5 on 2025-09-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackinghistory',
            old_name='currentbalance',
            new_name='current_balance',
        ),
        migrations.RemoveField(
            model_name='currentbalance',
            name='currentbalance',
        ),
        migrations.AddField(
            model_name='currentbalance',
            name='current_balance',
            field=models.FloatField(default=1),
        ),
    ]
