# Generated by Django 5.2.5 on 2025-09-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_currentbalance_trackinghistory_current_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentbalance',
            name='current_balance',
            field=models.FloatField(default=0),
        ),
    ]
